apiVersion: apps/v1
kind: Deployment
metadata:
  name: louvain-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "louvain-scheduler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "louvain-scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "louvain-scheduler.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: louvain-scheduler
      volumes:
        - name: scheduler-config
          configMap:
            name: scheduler-config
      containers:
        - name: louvain-scheduler
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config=/etc/kubernetes/scheduler-config.yaml
            - --v=3
          ports:
            - name: health
              containerPort: {{ .Values.ports.healthProbe }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.ports.healthProbe }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.ports.healthProbe }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: scheduler-config
              mountPath: /etc/kubernetes
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
