# permissions for end users to view graphs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: graph-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: graph
    app.kubernetes.io/part-of: graph
    app.kubernetes.io/managed-by: kustomize
  name: graph-viewer-role
rules:
- apiGroups:
  - sched.kasterism.io
  resources:
  - graphs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sched.kasterism.io
  resources:
  - graphs/status
  verbs:
  - get
