# permissions for end users to edit graphs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: graph-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: graph
    app.kubernetes.io/part-of: graph
    app.kubernetes.io/managed-by: kustomize
  name: graph-editor-role
rules:
- apiGroups:
  - sched.kasterism.io
  resources:
  - graphs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sched.kasterism.io
  resources:
  - graphs/status
  verbs:
  - get
