---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sched.kasterism.io
  resources:
  - graphs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sched.kasterism.io
  resources:
  - graphs/finalizers
  verbs:
  - update
- apiGroups:
  - sched.kasterism.io
  resources:
  - graphs/status
  verbs:
  - get
  - patch
  - update
